/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_location (void);
GtkWidget* create_locationEmp (void);
GtkWidget* create_ajouterloc (void);
GtkWidget* create_Modifierlocation (void);
GtkWidget* create_Emp (void);
GtkWidget* create_v4x4 (void);
GtkWidget* create_vcommercial (void);
GtkWidget* create_ajoutcomm (void);
GtkWidget* create_ajout4x4 (void);
GtkWidget* create_modifcomm (void);
GtkWidget* create_modif4x4 (void);
GtkWidget* create_menuclientloc (void);
GtkWidget* create_familiale (void);
GtkWidget* create_reservfamiliale (void);
GtkWidget* create_c4x4 (void);
GtkWidget* create_reserv4x4 (void);
GtkWidget* create_commercial (void);
GtkWidget* create_reservcomm (void);
