/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_location (void);
GtkWidget* create_locationEmp (void);
GtkWidget* create_ajouterloc (void);
GtkWidget* create_Modifierlocation (void);
